// =============================================================================
// S&P 100 Company Names
// =============================================================================

export const STOCK_NAMES: Record<string, string> = {
  AAPL: 'Apple Inc.',
  ABBV: 'AbbVie Inc.',
  ABT: 'Abbott Laboratories',
  ACN: 'Accenture plc',
  ADBE: 'Adobe Inc.',
  AIG: 'American International Group Inc.',
  AMD: 'Advanced Micro Devices Inc.',
  AMGN: 'Amgen Inc.',
  AMT: 'American Tower Corporation',
  AMZN: 'Amazon.com Inc.',
  AVGO: 'Broadcom Inc.',
  AXP: 'American Express Company',
  BA: 'The Boeing Company',
  BAC: 'Bank of America Corporation',
  BK: 'The Bank of New York Mellon Corporation',
  BKNG: 'Booking Holdings Inc.',
  BLK: 'BlackRock Inc.',
  BMY: 'Bristol-Myers Squibb Company',
  'BRK.B': 'Berkshire Hathaway Inc.',
  C: 'Citigroup Inc.',
  CAT: 'Caterpillar Inc.',
  CHTR: 'Charter Communications Inc.',
  CL: 'Colgate-Palmolive Company',
  CMCSA: 'Comcast Corporation',
  COF: 'Capital One Financial Corporation',
  COP: 'ConocoPhillips',
  COST: 'Costco Wholesale Corporation',
  CRM: 'Salesforce Inc.',
  CSCO: 'Cisco Systems Inc.',
  CVS: 'CVS Health Corporation',
  CVX: 'Chevron Corporation',
  DE: 'Deere & Company',
  DHR: 'Danaher Corporation',
  DIS: 'The Walt Disney Company',
  DOW: 'Dow Inc.',
  DUK: 'Duke Energy Corporation',
  EMR: 'Emerson Electric Co.',
  EXC: 'Exelon Corporation',
  F: 'Ford Motor Company',
  FDX: 'FedEx Corporation',
  GD: 'General Dynamics Corporation',
  GE: 'General Electric Company',
  GILD: 'Gilead Sciences Inc.',
  GM: 'General Motors Company',
  GOOG: 'Alphabet Inc.',
  GOOGL: 'Alphabet Inc.',
  GS: 'The Goldman Sachs Group Inc.',
  HD: 'The Home Depot Inc.',
  HON: 'Honeywell International Inc.',
  IBM: 'International Business Machines Corporation',
  INTC: 'Intel Corporation',
  JNJ: 'Johnson & Johnson',
  JPM: 'JPMorgan Chase & Co.',
  KHC: 'The Kraft Heinz Company',
  KO: 'The Coca-Cola Company',
  LIN: 'Linde plc',
  LLY: 'Eli Lilly and Company',
  LMT: 'Lockheed Martin Corporation',
  LOW: "Lowe's Companies Inc.",
  MA: 'Mastercard Incorporated',
  MCD: "McDonald's Corporation",
  MDLZ: 'Mondelez International Inc.',
  MDT: 'Medtronic plc',
  MET: 'MetLife Inc.',
  META: 'Meta Platforms Inc.',
  MMM: '3M Company',
  MO: 'Altria Group Inc.',
  MRK: 'Merck & Co. Inc.',
  MS: 'Morgan Stanley',
  MSFT: 'Microsoft Corporation',
  NEE: 'NextEra Energy Inc.',
  NFLX: 'Netflix Inc.',
  NKE: 'NIKE Inc.',
  NVDA: 'NVIDIA Corporation',
  ORCL: 'Oracle Corporation',
  PEP: 'PepsiCo Inc.',
  PFE: 'Pfizer Inc.',
  PG: 'The Procter & Gamble Company',
  PM: 'Philip Morris International Inc.',
  PYPL: 'PayPal Holdings Inc.',
  QCOM: 'QUALCOMM Incorporated',
  RTX: 'RTX Corporation',
  SBUX: 'Starbucks Corporation',
  SCHW: 'The Charles Schwab Corporation',
  SO: 'The Southern Company',
  SPG: 'Simon Property Group Inc.',
  T: 'AT&T Inc.',
  TGT: 'Target Corporation',
  TMO: 'Thermo Fisher Scientific Inc.',
  TMUS: 'T-Mobile US Inc.',
  TSLA: 'Tesla Inc.',
  TXN: 'Texas Instruments Incorporated',
  UNH: 'UnitedHealth Group Incorporated',
  UNP: 'Union Pacific Corporation',
  UPS: 'United Parcel Service Inc.',
  USB: 'U.S. Bancorp',
  V: 'Visa Inc.',
  VZ: 'Verizon Communications Inc.',
  WFC: 'Wells Fargo & Company',
  WMT: 'Walmart Inc.',
  XOM: 'Exxon Mobil Corporation',
} as const;

export type StockTicker = keyof typeof STOCK_NAMES;
